### ISSUE TITLE
Code not working?

### ISSUE THREAD

**Issue by J-A16** [cisc3620/8-texturing#12]
@rivlev I assumed the parameters we got are like the ones in the posted example code, I did the conversions then the diffuse, ambient and specular parts of the color using the textures, but it's not working.

**Comment by rivlev** [comment]
Unclear what you mean here. You don't have to make assumptions, all parameters are given. Make sure your conversions between spaces are correct.

**Comment by J-A16** [comment]
here's the todo, but there are no eyedir or lightdir in model space given:

// TODO: transform tangent, bitangent, position, eyedir, lightdir from model space (given) into camera space
// TODO: get camerspace normal from tangent and bitangent crossproduct. Construct TBN camerspace-->tangentspace matrix
// TODO: transform eyedir, lightdir from cameraspace to tangentspace

**Comment by rivlev** [comment]
Light pos is given in world space. Follow the tutorial to transform into camera space. The eye dir is implicit in camera space, see the tutorial. Tangent and bitangent are given in model space.
