### ISSUE TITLE
unknown image type error

### ISSUE THREAD

**Issue by TarekCodes** [cisc3620/8-texturing#14]
I'm trying to load brick_normals.png using stbi_load() but I'm getting "unknown image type". Is there a different function that I'm supposed to be using instead? Thanks.

@rivlev

**Comment by rivlev** [comment]
It should load with stbi_load.
Check if the image is corrupted by trying to open it with e.g. Preview
It seems that in some cases cmake may corrupt an image file when copying it into the Build directory. Try setting an absolute path in the code to the brick_normals.png in the Glitter/Textures directory

**Comment by TarekCodes** [comment]
I tried opening it but I also got an error that it's not supported. I tried downloading it directly from the repository and replacing the one I have and that didn't work either. I think the one you have in the repository is corrupted. @rivlev

**Comment by rivlev** [comment]
Thanks. Github seems to have an image problem popping up occasionally. I now have it stored [here](http://www.sci.brooklyn.cuny.edu/~levitan/cisc3620/materials/brick_normals.png)
You can download it and copy it into Glitter/Textures
Please confirm that you can get it from the link and close if that fixes your issue.

**Comment by TarekCodes** [comment]
I think you posted the wrong link. [This](http://www.sci.brooklyn.cuny.edu/~levitan/cisc3620/materials/brick_normals.png) worked for me though, thanks!
