### ISSUE TITLE
normal map

### ISSUE THREAD

**Issue by TarekCodes** [cisc3620/8-texturing#16]
My program wasn't working so I went back to try each component. I tried assigning the outColor in the fragment shader to the normal map and [this is what I got](http://i.imgur.com/647z6t3.png). Is this how it's supposed to look like? Thanks @rivlev

**Comment by rivlev** [comment]
No, open up the brick texture in an image viewer. It should look like that, textured onto all four sides.

**Comment by TarekCodes** [comment]
I fixed it. I changed one of stbi_load's parameters from STBI_rgb to STBI_rgb_alpha when I was trying to fix the previous problem and forgot to switch it back, thanks!
