### ISSUE TITLE
tangent/bitangent are 0

### ISSUE THREAD

**Issue by TarekCodes** [cisc3620/8-texturing#17]
Everything is working except that the tangent and bitangent are 0. I tried to color my cube using both and each time the cube comes out completely black which is how I know they're 0. I can't create a TBN matrix because of that and that's making my lighting look weird. Any idea why that might be happening? Thanks a lot!  @rivlev

**Comment by rivlev** [comment]
Sorry, that is a versioning error (in the bufferdata commands). I just pushed a fix
