### ISSUE TITLE
Project won't compile

### ISSUE THREAD

**Issue by J-A16** [cisc3620/8-texturing#4]
Professor, the project won't even compile as is for me, I keep getting errors around line 222 and a little further down.

@rivlev

**Comment by rivlev** [comment]
What errors are you getting?

**Comment by J-A16** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		function call must have a constant value in a constant expression	Glitter	c:\Users\Pleasure Cruise\Desktop\8-texturing-J-A16-bump\Glitter\Sources\main.cpp	222	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2131	expression did not evaluate to a constant	Glitter	C:\Users\Pleasure Cruise\Desktop\8-texturing-J-A16-bump\Glitter\Sources\main.cpp	222	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C3863	array type 'GLfloat ['function'*]' is not assignable	Glitter	C:\Users\Pleasure Cruise\Desktop\8-texturing-J-A16-bump\Glitter\Sources\main.cpp	226	

Error messages like that. @rivlev

**Comment by J-A16** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		function call must have a constant value in a constant expression	Glitter	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2131	expression did not evaluate to a constant	Glitter	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C3863	array type 'GLfloat ['function'*]' is not assignable	Glitter	

Error messages like that. @rivlev

**Comment by J-A16** [comment]
at lines 222, 223, 226 and 227

**Comment by rivlev** [comment]
Please refer to line numbers in the original code; 223, 226 and 227 are comments or blank
What changes have you made?
What process of building and compiling did you follow?

**Comment by J-A16** [comment]
This code is the code from the bump branch that is preventing it from compiling, I made no changes and I followed the same cmake steps I used for every project:

```
GLfloat tangent_arr[tangents.size()*3];
	GLfloat bitangent_arr[bitangents.size()*3];
	for (int i = 0; i < tangents.size(); i++) {
		for (int j = 0; j < 3; j++) {
			tangent_arr[i*3+j] = tangents[i][j];
			bitangent_arr[i*3+j] = bitangents[i][j];
```

**Comment by rivlev** [comment]
Please give more information about your environment, since this compiles without issues on my machine.

**Comment by J-A16** [comment]
Windows 10, Microsoft visual studio community 2015

**Comment by rivlev** [comment]
The answer seems to be here: http://stackoverflow.com/questions/33423502/expression-did-not-evaluate-to-a-constant-c
Variable-length arrays are a c++11 feature. 
Pushing a patch to accommodate
