### ISSUE TITLE
My Box is Black

### ISSUE THREAD

**Issue by Emmgreens** [cisc3620/8-texturing#5]
I had this problem with the last lab too. The box is different colors in the master branch as it should be. But in the texture branch, the box is just black. I haven't made any changes in the texture branch. Is this how it should be? (it's supposed to be the bunny, right?) If so, i'm not sure exactly what we have to do to change it.   

Thank you for the help!

**Comment by jelmani** [comment]
Yup, same issue. On the Bump branch there is no box at all. On the texture branch the box is black. I tried changing the source of the bunny pic in the code to the full path but it didn't work.

@rivlev

**Comment by rivlev** [comment]
When you run `cmake ..` from the Build directory
and then `cmake --build .`
does it work? Are the bunny and brick textures being copied into the Build directory as expected?

**Comment by Emmgreens** [comment]
Yes it's now in the build directory! But when I compile the screen is just white.

**Comment by rivlev** [comment]
In which branch? That is correct for the bump branch, but the texture branch should show the bunny box

**Comment by Emmgreens** [comment]
The box is black in the texture branch. In the last lab too

**Comment by rivlev** [comment]
Try setting the path in the code manually like you had to for lab 7

**Comment by J-A16** [comment]
I set the path manually, I no longer get an error sent to console, but my code still isn't displaying anything new

**Comment by J-A16** [comment]
I set the path manually, I no longer get an error sent to console, but my code still isn't displaying anything new @rivlev

**Comment by rivlev** [comment]
In the texture branch?

**Comment by J-A16** [comment]
in the bump branch @rivlev

**Comment by rivlev** [comment]
If it works in the texture branch, then the problem isn't with texture loading. You need to separately debug your shaders in the bump branch.
