### ISSUE TITLE
Still have the issue

### ISSUE THREAD

**Issue by J-A16** [cisc3620/8-texturing#6]
@rivlev 
The file hasn't changed, when are you going to push the changes professor?

**Comment by rivlev** [comment]
The changes were pushed yesterday. Make sure you are looking at the bump branch. This was commit 59a85609d9b09bc627704c9fdd26b60209b16dfd

**Comment by J-A16** [comment]
When you say the window should be blank, do you mean a white box with a gray border? Because that's what I got. That's what's suppose to happen?

@rivlev

**Comment by rivlev** [comment]
Yes. Please open a separate issue for new questions.
