### ISSUE TITLE
Eye Direction

### ISSUE THREAD

**Issue by J-A16** [cisc3620/8-texturing#9]
Eye direction is not explicitly given, how do we get it?

@rivlev

**Comment by J-A16** [comment]
Origin - camera space position of vertex?

**Comment by J-A16** [comment]
how do we transform all of the parameters from model space to camera space? @rivlev

**Comment by J-A16** [comment]
We just multiply the parameters by the model and the view to get them to camera space?

**Comment by J-A16** [comment]
the m and v in the code of the tutorial is the model and view correct? so we just follow how the code transforms to bring the parameters from  model space into camera space?

**Comment by J-A16** [comment]
@rivlev you say the eyeDir and lightDir in model space are given, but they aren't. lightPos is in worldspace?

**Comment by J-A16** [comment]
@rivlev need some serious help on this project

**Comment by rivlev** [comment]
The answers to all these questions are in the tangent/bitangent tutorial linked from the Readme and/or in the associated code.

**Comment by J-A16** [comment]
in the todo you say things are given that are not

**Comment by J-A16** [comment]
the lightPos we are given in the vertex shader is in worldspace? @rivlev

**Comment by rivlev** [comment]
* Please be specific.
* The light pos is set in the application and sent to the vertex shader. It is in worldspace, so it only has to be multiplied by the view matrix to be in camera space (exactly as in the tutorial).

**Comment by J-A16** [comment]
yeah, that's exactly what I did. I did everything the tutorial did, and did the lighting equations in the fragment shader for diffuse, ambient and specular, but it's not showing me anything new in the display. How do I get the rotating cube and all to display?

**Comment by J-A16** [comment]
yeah, that's exactly what I did. I did everything the tutorial did, and did the lighting equations in the fragment shader for diffuse, ambient and specular, but it's not showing me anything new in the display. How do I get the rotating cube and all to display? @rivlev

**Comment by rivlev** [comment]
You need to debug your shaders. 
* Compile and run the texture branch to make sure you are at the starting point.
* From the bump branch, set the output color to intermediate values such as tangent, bitangent, normal, eyedir, lightdir, (make into vec4 by concatenating 1.0), texture(textureMap, texcoord), texture(normalMap, texcoord) 
   to make sure that the intermediate values are correct (remember that r=x, g=y, b=z)

**Comment by J-A16** [comment]
In texture branch I got a rotating cube, in bump branch I have no rotating cube. I will try debugging now. @rivlev

**Comment by J-A16** [comment]
in texture I also got the bunny texture without setting the full path

**Comment by J-A16** [comment]
Am I suppose to get a rotating cube by default in the bump branch? How do I cause the rotating cube to render if not? @rivlev

**Comment by rivlev** [comment]
Without changes, the bump branch will display a blank gray screen. This is because the output color is set to diffuse + ambient + specular, which have not been set. You can also set the output color to vec4(ambient, 1.0) for a rotating gray cube (without other changes)

**Comment by J-A16** [comment]
I tried to change it to vec4(.3,0.5,0.6,1.0) nothing is changing in the display screen. comment out all other code in the shaders to see what happens?

**Comment by J-A16** [comment]
start fresh and just test ambient? @rivlev

**Comment by J-A16** [comment]
I started a fresh download and used outColor = vec4(ambientStrength, 1.0), that got me the gray rotating cube. Back to my original code, you think it's something in my shader code that's causing a problem? @rivlev

**Comment by rivlev** [comment]
Yes.

**Comment by J-A16** [comment]
@rivlev how do you recommend I debug it if I can't get a gray rotating cube when I set outColor = vec4(ambientStrength, 1.0)?

**Comment by J-A16** [comment]
I'm thinking start with the gray rotating box, adding code line by line until a problem arises

**Comment by rivlev** [comment]
Yes.

**Comment by J-A16** [comment]
@rivlev for some reason these lines cause a problem, what's wrong with tangent and bitangent?:

"vec3 vertexTangent_cameraspace = view * model * tangent;"
"vec3 vertexBitangent_cameraspace = view * model * bitangent; "

**Comment by J-A16** [comment]
they are in model space right?

**Comment by J-A16** [comment]
I was trying to make it correspond to this part of the example code:

// model to camera = ModelView
	vec3 vertexTangent_cameraspace = MV3x3 * vertexTangent_modelspace;
	vec3 vertexBitangent_cameraspace = MV3x3 * vertexBitangent_modelspace;
vec3 vertexNormal_cameraspace = MV3x3 * vertexNormal_modelspace;

**Comment by J-A16** [comment]
I did this to get the normal like you said, I think:

"vec3 vertexNormal_cameraspace = cross(vertexBitangent_cameraspace, vertexTangent_cameraspace);"

**Comment by J-A16** [comment]
Oh, the tangent and bitangent are vec3s. once I fix that multiplying by the model then view will mirror the example MV3X3 right?

**Comment by J-A16** [comment]
Also, I've got a rotating, lighted cube now by getting it to accept all parts of the outColor, but there is no texture or brick looking lighting @rivlev

**Comment by J-A16** [comment]
Which normal do we use in calculating the specular component? How do we calculate it? @rivlev

**Comment by J-A16** [comment]
I see the bunny, but no brick texture now.

**Comment by J-A16** [comment]
It's just mostly covered with specular highlights

**Comment by J-A16** [comment]
this is the chunk of the fragment shader I wrote, with their already written assugnment to outColor:

"vec3 TextureNormal_tangentspace = texture(normalMap, TexCoord).rgb*2.0 - 1.0;"
"vec3 TextureColor = texture(textureMap, TexCoord).rgb;"

"    vec3 norm = TextureNormal_tangentspace;"
"    vec3 lightDir = LightDir_tangentspace;"
"    float diff = max(dot(norm, lightDir), 0.0);"
"    vec3 diffuse = diff * TextureColor;"

"    vec3 ambient = ambientStrength;"

"    vec3 reflection = (2 * norm * dot(norm, lightDir)) - lightDir;"
"    float spec = max(dot(EyeDir_tangentspace, reflection), 0.0);"
"    vec3 specular = lightColor * pow(spec, 2);"

"		 outColor = vec4(diffuse + ambient + specular, 1.0);"

**Comment by rivlev** [comment]
Please do not post large snippets of code.

**Comment by rivlev** [comment]
Not clear what your question is. If you want a general code review / debugging the appropriate venue for that is office hours.

**Comment by J-A16** [comment]
multiplying by the model then view will mirror the example MV3X3 right?

**Comment by rivlev** [comment]
mat3(model * view)
